version: '3.8'

services:
  backend:
    image: ghcr.io/nxkev/wmusa-reporting-backend:latest
    ports:
      - "${PROD_BACKEND_PORT:-3001}:3001"
    environment:
      - NODE_ENV=${PROD_NODE_ENV:-production}
      - DATABASE_URL=file:${PROD_DB_PATH:-/app/data/db.sqlite}
      - UPLOAD_DIR=${PROD_UPLOAD_DIR:-/app/uploads}
    volumes:
      - ${PROD_DEPLOY_PATH:-/opt/wmusa-reporting}/data:/app/data
      - ${PROD_DEPLOY_PATH:-/opt/wmusa-reporting}/uploads:/app/uploads
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    image: ghcr.io/nxkev/wmusa-reporting-frontend:latest
    ports:
      - "${PROD_FRONTEND_PORT:-3000}:3000"
    environment:
      - NODE_ENV=${PROD_NODE_ENV:-production}
      - NEXT_PUBLIC_API_URL=http://${PROD_SERVER_IP}:${PROD_BACKEND_PORT:-3001}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    depends_on:
      - backend

volumes:
  backend_data:
  backend_uploads: 