version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - "3001:3001"
    volumes:
      - ./data:/app/data
      - ./input-files:/app/input-files
    environment:
      - NODE_ENV=production
      - MAX_FILE_SIZE=100000000
      - PORT=3001
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 800M
        reservations:
          memory: 600M

  frontend:
    build: 
      context: ./frontend
      target: runner
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:3001
    depends_on:
      - backend
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 200M
        reservations:
          memory: 150M 