version: '3.8'

services:
  frontend:
    image: ghcr.io/nxkev/wmusa-reporting-frontend:latest
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://backend:3001
    depends_on:
      - backend

  backend:
    image: ghcr.io/nxkev/wmusa-reporting-backend:latest
    restart: always
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
    volumes:
      - ./data:/app/data
      - ./uploads:/app/uploads
    deploy:
      resources:
        limits:
          memory: 800M
        reservations:
          memory: 600M 